version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cultiv8-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # PostgreSQL database (optional - use Neon in production)
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: cultiv8-db
  #   environment:
  #     POSTGRES_DB: cultiv8
  #     POSTGRES_USER: cultiv8
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  redis_data:
    driver: local
  # postgres_data:
  #   driver: local

